version: '3'
services:
  burryedge-discord-bot:
      container_name: burryedge-discord-bot
      build:
        context: .
        dockerfile: Dockerfile
      env_file: .env
      restart: always
      # ports:
      #     - "8081:8080"
